-- Add new NotificationType variants for quotes, invoices, and payments
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'QUOTE_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'QUOTE_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'QUOTE_EXPIRING_SOON';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INVOICE_SENT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INVOICE_OVERDUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INVOICE_PAID';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_RECEIVED';
