export const USER_ROLES = [
  "OWNER",
  "FACTORY_MANAGER",
  "SALES_MANAGER",
  "SUPERVISOR",
  "WORKER",
  "ACCOUNTANT",
  "CUSTOMER",
] as const;

export type UserRole = (typeof USER_ROLES)[number];

export const PERMISSIONS = [
  "dashboard:view",
  "notifications:view",
  "reports:view",
  "ops:view",
  "ops:manage",
  "projects:view",
  "projects:manage",
  "crm:view",
  "crm:manage",
  "orders:view",
  "orders:create",
  "orders:update",
  "production:view",
  "production:assign",
  "payments:view",
  "users:manage",
  "settings:manage",
  "portal:view",
  "costs:view",
  "costs:manage",
  "me:view",
  "search:view",
  "finance:view",
  "quotes:view",
  "quotes:draft",
  "quotes:approve",
  "quotes:cancel",
  "vendors:view",
  "vendors:manage",
  "products:view",
  "products:manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const rolePermissions: Record<UserRole, Permission[]> = {
  OWNER: PERMISSIONS.slice(),
  FACTORY_MANAGER: PERMISSIONS.slice(),
  SALES_MANAGER: [
    "dashboard:view",
    "notifications:view",
    "reports:view",
    "ops:view",
    "projects:view",
    "crm:view",
    "crm:manage",
    "orders:view",
    "orders:create",
    "orders:update",
    "payments:view",
    "portal:view",
    "me:view",
    "search:view",
    "quotes:view",
    "quotes:draft",
    "vendors:view",
    "products:view",
  ],
  SUPERVISOR: [
    "dashboard:view",
    "notifications:view",
    "reports:view",
    "ops:view",
    "ops:manage",
    "projects:view",
    "projects:manage",
    "crm:view",
    "orders:view",
    "production:view",
    "production:assign",
    "me:view",
    "search:view",
  ],
  WORKER: ["production:view", "me:view"],
  ACCOUNTANT: [
    "dashboard:view",
    "notifications:view",
    "reports:view",
    "crm:view",
    "orders:view",
    "payments:view",
    "costs:view",
    "costs:manage",
    "me:view",
    "search:view",
    "finance:view",
    "quotes:view",
    "vendors:view",
    "vendors:manage",
    "products:view",
  ],
  CUSTOMER: ["portal:view", "me:view"],
};

export function hasPermission(role: UserRole, permission: Permission) {
  return rolePermissions[role].includes(permission);
}
